sonar.organization=alibe-ages
sonar.projectKey=Alibe-AGES_Backend

sonar.sources=src
sonar.tests=test

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/unit/lcov.info,coverage/integration/lcov.info,coverage/e2e/lcov.info
sonar.coverage.exclusions=src/main.ts,src/**/*.module.ts,src/**/*.dto.ts
